### ISSUE TITLE
데이터베이스 완성

### ISSUE THREAD

**Issue by jhMin95** [pong-nyan/pong-nyan#105]
## Todo
- [ ] Profile View Table 만들기
- [ ] typeorm 적용하기
- [ ] 전체적인 DB 명세 확정하기
- [ ] typeorm 명세 확정하기 (relation join 명세에 추가)
